trigger: none


pool: infra_pool

stages:
- stage: scaning_stage
  jobs:
  - job: scanning_stage
    steps:
    - task: tfsec@1
      displayName: Run tfsec
      inputs:
        version: 'v1.26.0'

- stage: Build_Stage
  displayName: Terraform init to plan
  jobs:
  - job: Terraforminit
    displayName: Terraform Init
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform installation
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
        backendServiceArm: 'workeload_federation'
        backendAzureRmResourceGroupName: 'shiva-rg'
        backendAzureRmStorageAccountName: 'shivastg7118'
        backendAzureRmContainerName: 'file'
        backendAzureRmKey: 'terraformtfstate'
        environmentServiceNameAzureRM: 'workeload_federation'   # 👈 Added (required)

    - task: TerraformTask@5
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
        

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
        environmentServiceNameAzureRM: 'workeload_federation'

- stage: Manual_validation
  pool: server
  jobs:
   - job: Manual_validation
     steps:
     - task: ManualValidation@1
       inputs:
         notifyUsers: 'shivanand1801@gmail.com'
         approvers: 'shivanand1801@gmail.com'

- stage: Terraform_apply
  jobs:
   - job: Terraform_apply
     steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
         environmentServiceNameAzureRM: 'workeload_federation'

     
     




